stages:
  - build
  - test
  - publish

################################################################################

build-dist:
  stage: build
  image: python:3.11-slim-bullseye
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist

################################################################################

.build-docker:
  stage: build
  image: docker
  services: ['docker:dind']
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: |
    echo -e "###############################\nPulling cache for context..."
    cp Dockerfile.$VARIANT.dockerignore .dockerignore
    CONTEXT=$(echo -e 'FROM scratch\nADD * .' | docker build . --file - 2>&1 | grep 'writing image' | cut -d: -f2 | cut -d' ' -f1)
    if `docker pull $CI_REGISTRY_IMAGE/cache/$VARIANT:by-context-$CONTEXT`
    then
      echo -e "###############################\nPushing cache images for stage $STAGE..."
      docker tag $CI_REGISTRY_IMAGE/cache/$VARIANT:by-context-$CONTEXT $CI_REGISTRY_IMAGE/cache/$VARIANT:by-commit-$CI_COMMIT_SHA
      docker push $CI_REGISTRY_IMAGE/cache/$VARIANT:by-commit-$CI_COMMIT_SHA
    else
      for STAGE in $(cat Dockerfile.$IMAGE | grep -E 'FROM \S+ AS \S+' | cut -d' ' -f4)
      do
        echo -e "###############################\nPulling cache images for stage $STAGE..."
        docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-master-$STAGE || true
        docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-$CI_COMMIT_REF_NAME-$STAGE || true
        docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_SHA-$STAGE || true
        docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_BEFORE_SHA-$STAGE || true
  
        echo -e "###############################\nBuilding image for stage $STAGE..."
        docker build . \
          --file Dockerfile.$IMAGE \
          --target $STAGE \
          --tag $IMAGE:$STAGE
  
        echo -e "###############################\nPushing image for stage $STAGE..."
        docker tag $IMAGE:$STAGE $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-$CI_COMMIT_REF_NAME-$STAGE
        docker tag $IMAGE:$STAGE $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_SHA-$STAGE
        docker push $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-$CI_COMMIT_REF_NAME-$STAGE
        docker push $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_SHA-$STAGE
      done
    fi

build-tester:
  extends: .build-docker
  variables:
    VARIANT: tester

build-release:
  extends: .build-docker
  variables:
    VARIANT: release

################################################################################

test-pip:
  stage: test
  needs: [build-tester, build-dist]
  image: $CI_REGISTRY_IMAGE/cache/tester:by-commit-$CI_COMMIT_SHA
  services: ['docker:dind']
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - pip install dist/*.tar.gz
    - rm dist/*.tar.gz
  script:
    - git checkout -- Makefile tests
    - make tests
  coverage: '/TOTAL .+ (\d+\.\d+)%/'

test-src:
  stage: test
  needs: [build-tester]
  image: $CI_REGISTRY_IMAGE/cache/tester:by-commit-$CI_COMMIT_SHA
  services: ['docker:dind']
  script:
    - make tests

################################################################################

include: .gitlab-ci-post.yml