stages:
  - manual
  - build
  - test

################################################################################

build-ci-env:
  stage: manual
  when: manual
  image: docker
  services: ['docker:dind']
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker run -it --detach --name ci-env docker
    - docker exec ci-env apk add git make pigz py3-pip
    - docker commit ci-env $CI_REGISTRY_IMAGE/ci-env
    - docker push $CI_REGISTRY_IMAGE/ci-env


################################################################################

build-dist:
  stage: build
  image: python:3.11-slim-bullseye
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist

################################################################################

.build-docker:
  stage: build
  image: $CI_REGISTRY_IMAGE/ci-env
  services: ['docker:dind']
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE:master || true
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_REF_NAME || true
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA || true
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_BEFORE_SHA || true
    - >
      docker build .
      --file Dockerfile.$IMAGE
      --cache-from $CI_REGISTRY_IMAGE/$IMAGE:master
      --cache-from $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_REF_NAME
      --cache-from $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA
      --cache-from $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_BEFORE_SHA
      --tag $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_REF_NAME
      --tag $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA
      --tag $IMAGE
    - docker push $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA
    - docker save $IMAGE | pigz > $IMAGE.tar.gz
  artifacts:
    paths:
      - $IMAGE.tar.gz

build-tester:
  extends: .build-docker
  variables:
    IMAGE: tester

build-release:
  extends: .build-docker
  variables:
    IMAGE: release

################################################################################

.test-docker:
  stage: test
  image: $CI_REGISTRY_IMAGE/ci-env
  variables:
    GIT_STRATEGY: fetch
  services: ['docker:dind']
  before_script:
    - docker load < $IMAGE.tar.gz
    - rm $IMAGE.tar.gz
    - docker run --detach --rm --name $IMAGE -v $PWD:/PRJ --entrypoint dd $IMAGE if=/dev/zero of=/dev/null

test-pip:
  extends: .test-docker
  needs: [build-tester, build-dist]
  variables:
    IMAGE: tester
  script:
    - docker exec $IMAGE pip install dist/*.tar.gz
    - rm dist/*.tar.gz
    - git checkout -- Makefile tests
    - docker exec $IMAGE make tests
  coverage: '/TOTAL .+ (\d+\.\d+)%/'

test-release:
  extends: .test-docker
  needs: [build-release]
  variables:
    IMAGE: release
  script:
    - git checkout -- Makefile tests
    - docker exec $IMAGE make tests