publish:
  stage: publish
  image: docker
  services: ['docker:dind']
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/cache/release:by-commit-$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/cache/release:by-commit-$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/sobiraka:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/sobiraka:$CI_COMMIT_SHA

pages:
  stage: publish
  needs: [docs]
  image: alpine:3.16
  variables:
    GIT_STRATEGY: none
  script:
    - mv docs public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == 'master'
