stages:
  - maker
  - build
  - test

build-maker:
  stage: maker
  when: manual
  image: docker:19.03
  services: ['docker:dind']
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull alpine:3.16
    - docker run -it --detach --name maker docker
    - docker exec maker apk add make py3-pip
    - docker commit maker $CI_REGISTRY_IMAGE:maker
    - docker push $CI_REGISTRY_IMAGE:maker

build-tester:
  stage: build
  image: docker
  services: ['docker:dind']
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:tester
    - docker build --file Dockerfile.dev --cache-from $CI_REGISTRY_IMAGE:tester --tag $CI_REGISTRY_IMAGE:tester .
    - docker push $CI_REGISTRY_IMAGE:tester
  rules:
    - changes:
        - .gitlab-ci.yml
        - .dockerignore
        - Dockerfile.dev
        - setup.py

build-dist:
  stage: build
  image: python:3.11-alpine
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:tester
  before_script:
    - pip install dist/*.tar.gz
    - git sparse-checkout set Makefile tests
    - ls -lAh
  script:
    - make tests
  coverage: '/TOTAL .+ (\d+\.\d+)%/'