stages:
  - build
  - test
  - publish

################################################################################

build-dist:
  stage: build
  image: python:3.11-slim-bullseye
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist

################################################################################

.build-docker:
  stage: build
  image: docker
  services: ['docker:dind']
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: |
    for STAGE in $(cat Dockerfile.$IMAGE | grep -E 'FROM \S+ AS \S+' | cut -d' ' -f4)
    do
      echo -e \nPulling cache images for stage $STAGE...
      docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-master-$STAGE || true
      docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-$CI_COMMIT_REF_NAME-$STAGE || true
      docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_SHA-$STAGE || true
      docker pull $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_BEFORE_SHA-$STAGE || true

      echo -e \nBuilding image for stage $STAGE...
      docker build . \
        --file Dockerfile.$IMAGE \
        --target $STAGE \
        --cache-from $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-master-$STAGE \
        --cache-from $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-$CI_COMMIT_REF_NAME-$STAGE \
        --cache-from $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_SHA-$STAGE \
        --cache-from $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_BEFORE_SHA-$STAGE \
        --tag $IMAGE:$STAGE

      echo -e \nPushing image for stage $STAGE...
      docker tag $IMAGE:$STAGE $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-$CI_COMMIT_REF_NAME-$STAGE
      docker tag $IMAGE:$STAGE $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_SHA-$STAGE
      docker push $CI_REGISTRY_IMAGE/cache/$IMAGE:branch-$CI_COMMIT_REF_NAME-$STAGE
      docker push $CI_REGISTRY_IMAGE/cache/$IMAGE:commit-$CI_COMMIT_SHA-$STAGE
    done

build-tester:
  extends: .build-docker
  variables:
    IMAGE: tester

build-release:
  extends: .build-docker
  variables:
    IMAGE: release

################################################################################

test-pip:
  stage: test
  needs: [build-tester, build-dist]
  image: $CI_REGISTRY_IMAGE/cache/tester:commit-$CI_COMMIT_SHA-final
  services: ['docker:dind']
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - pip install dist/*.tar.gz
    - rm dist/*.tar.gz
  script:
    - git checkout -- Makefile tests
    - make tests
  coverage: '/TOTAL .+ (\d+\.\d+)%/'

test-src:
  stage: test
  needs: [build-tester]
  image: $CI_REGISTRY_IMAGE/cache/tester:commit-$CI_COMMIT_SHA-final
  services: ['docker:dind']
  script:
    - make tests

################################################################################

include: .gitlab-ci-post.yml