FROM alpine:3.16 AS get-pandoc
WORKDIR /tmp/pandoc
RUN arch=$(arch | sed s:aarch64:arm64: | sed s:x86_64:amd64:) \
    && wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-linux-$arch.tar.gz -O- | tar -xz --strip-components=1

FROM python:3.11-slim-bullseye AS get-dependencies-pip
RUN pip install --no-cache-dir pyyaml~=5.3.1 panflute~=2.2.3 coverage~=7.0.1

FROM python:3.11-slim-bullseye AS sobiraka

# Copy all other dependencies
COPY --from=get-pandoc /tmp/pandoc /usr/local
COPY --from=get-dependencies-pip /usr/local /usr/local

# Create user identical to the host user
ARG UID=1000
ARG GID=1000
RUN addgroup --gid $GID user
RUN adduser --uid $UID --gid $GID user

WORKDIR /WORKDIR
CMD python src/main.py