on:
  workflow_call:

jobs:
  build-docs-pdf:
    name: Build PDF
    runs-on: self-hosted
    container: ghcr.io/documentat/${{ vars.IMAGE_NAME }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: docs

      - run: sobiraka pdf docs/docs.yaml --output docs/build

      - uses: actions/upload-artifact@v4
        with:
          name: Documentation (PDF)
          path: docs/build

      - run: rm -rf * .* || true

  build-docs-web:
    name: Build HTML
    runs-on: self-hosted
    container: ghcr.io/documentat/${{ vars.IMAGE_NAME }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: docs

      - run: sobiraka web docs/docs.yaml --output docs/build --hide-index-html

      - uses: actions/upload-artifact@v4
        with:
          name: Documentation (web)
          path: docs/build
          compression-level: 9

      - run: rm -rf * .* || true

  publish-docs:
    name: Publish documentation
    needs: [build-docs-pdf, build-docs-web]
    runs-on: self-hosted

    steps:
      - name: Setup SSH
        run: |
          echo "${{ vars.KNOWN_HOSTS }}" >> ./gha_known_hosts
          echo "${{ secrets.SSH_KEY }}" > ./gha_identity
          chmod 600 ./gha_identity

      - uses: actions/download-artifact@v4
        with:
          name: Documentation (PDF)
          path: docs/build

      - uses: actions/download-artifact@v4
        with:
          name: Documentation (web)
          path: docs/build

      - name: Choose uploading URL
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo PUBLICATION_DEST=demo@demo.documentat.io:/home/demo/sobiraka/ >> $GITHUB_ENV
            echo PUBLICATION_URL=http://sobiraka.demo.documentat.io/ >> $GITHUB_ENV
          else
            echo PUBLICATION_DEST=demo@demo.documentat.io:/home/demo/sobiraka/~${{ github.ref_name }} >> $GITHUB_ENV
            echo PUBLICATION_URL=http://sobiraka.demo.documentat.io/~${{ github.ref_name }}/ >> $GITHUB_ENV
          fi

      - name: Upload directory
        run: >
          rsync
          docs/build/
          ${{ env.PUBLICATION_DEST }}
          --verbose
          --rsh 'ssh -i ./gha_identity -o UserKnownHostsFile=./gha_known_hosts'
          --human-readable
          --recursive
          --delete
          --exclude .htaccess
          --exclude .htpasswd
          --exclude ~*
          &&
          echo ::notice title=Documentation published on the demo server::${{ env.PUBLICATION_URL }}