on:
  workflow_call:
    inputs:
      PUBLIC_REPOSITORY_URL:
        type: string
        required: true
      DOCKER_PROD_IMAGE:
        type: string
        required: true

env:
  PUBLIC_REPOSITORY_URL: ${{ inputs.PUBLIC_REPOSITORY_URL }}
  DOCKER_PROD_IMAGE: ${{ inputs.DOCKER_PROD_IMAGE }}

jobs:
  build-docs-pdf:
    name: Build PDF
    runs-on: self-hosted
    container: ${{ (github.ref == 'refs/heads/master') && vars.DOCKER_PROD_IMAGE || vars.DOCKER_DEV_IMAGE }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: docs

      - run: sobiraka pdf docs/docs.yaml --output docs/build

      - uses: actions/upload-artifact@v4
        with:
          name: Documentation (PDF)
          path: docs/build

      - run: rm -rf * .* || true

  build-docs-web:
    name: Build HTML
    runs-on: self-hosted
    container: ${{ (github.ref == 'refs/heads/master') && vars.DOCKER_PROD_IMAGE || vars.DOCKER_DEV_IMAGE }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: docs

      - run: sobiraka web docs/docs.yaml --output docs/build --hide-index-html

      - uses: actions/upload-artifact@v4
        with:
          name: Documentation (web)
          path: docs/build
          compression-level: 9

      - run: rm -rf * .* || true

  publish-docs:
    name: Publish documentation
    needs: [build-docs-pdf, build-docs-web]
    runs-on: self-hosted

    steps:
      - name: Setup SSH
        run: |
          echo "${{ vars.KNOWN_HOSTS }}" >> ./gha_known_hosts
          echo "${{ secrets.SSH_KEY }}" > ./gha_identity
          chmod 600 ./gha_identity

      - uses: actions/download-artifact@v4
        with:
          name: Documentation (PDF)
          path: docs/build

      - uses: actions/download-artifact@v4
        with:
          name: Documentation (web)
          path: docs/build

      - name: Choose uploading URL
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo PUBLICATION_DEST=${{ vars.DOCS_MASTER_RSYNC }} >> $GITHUB_ENV
            echo PUBLICATION_URL=${{ vars.DOCS_MASTER_URL }} >> $GITHUB_ENV
          else
            echo PUBLICATION_DEST=${{ format(vars.DOCS_BRANCH_RSYNC, github.ref_name) }} >> $GITHUB_ENV
            echo PUBLICATION_URL=${{ format(vars.DOCS_BRANCH_URL, github.ref_name) }}/ >> $GITHUB_ENV
          fi

      - name: Upload directory
        run: >
          rsync
          docs/build/
          ${{ env.PUBLICATION_DEST }}
          --rsh 'ssh -i ./gha_identity -o UserKnownHostsFile=./gha_known_hosts -v'
          --human-readable
          --recursive
          --delete
          --exclude .htaccess
          --exclude .htpasswd
          --exclude ~*
          &&
          echo ::notice title=Documentation published::${{ env.PUBLICATION_URL }}