on:
  workflow_call:

jobs:
  build-sobiraka:
    name: Build sobiraka
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: make release IMAGE=sobiraka:${{ github.sha }}

  build-sobiraka-latex:
    name: Build sobiraka-latex
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: make release-latex IMAGE=sobiraka-latex:${{ github.sha }}

  publish-images:
    name: Publish images
    needs: [build-sobiraka, build-sobiraka-latex]
    runs-on: self-hosted
    steps:
      - name: Choose destination
        run: |
          if [ ${{ github.ref }} = 'refs/heads/master' ]; then
            echo PROD=1 >> $GITHUB_ENV
            echo IMAGE=${{ vars.DOCKER_PROD_IMAGE }} >> $GITHUB_ENV
            echo TAGS='${{ github.sha }} latest' >> $GITHUB_ENV
          else
            echo PROD= >> $GITHUB_ENV
            echo IMAGE=${{ vars.DOCKER_DEV_IMAGE }} >> $GITHUB_ENV
            echo TAGS='${{ github.sha }} ${{ github.ref_name }}' >> $GITHUB_ENV
          fi

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.PROD && vars.DOCKER_PROD_REGISTRY || 'ghcr.io' }}
          username: ${{ env.PROD && vars.DOCKER_PROD_USERNAME || github.actor }}
          password: ${{ env.PROD && secrets.DOCKER_PROD_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Publish sobiraka
        run: |
          for TAG in ${{ env.TAGS }}; do
            echo ::group::Publish ${{ env.IMAGE }}:$TAG
            docker tag sobiraka:${{ github.sha }} ${{ env.IMAGE }}:$TAG
            docker push ${{ env.IMAGE }}:$TAG
            echo ::endgroup::
          done

      - name: Publish sobiraka-latex
        run: |
          for TAG in ${{ env.TAGS }}; do
            echo ::group::Publish ${{ env.IMAGE }}-latex:$TAG
            docker tag sobiraka-latex:${{ github.sha }} ${{ env.IMAGE }}-latex:$TAG
            docker push ${{ env.IMAGE }}-latex:$TAG
            echo ::endgroup::
          done