on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        default: ${{ github.sha }}

jobs:
  build-image:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - { target: release, image: sobiraka }
          - { target: release-latex, image: sobiraka-latex }

    name: ${{ matrix.variant.image }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: >
          make ${{ matrix.variant.target }}
          IMAGE=ghcr.io/documentat/${{ matrix.variant.image }}:${{ inputs.image_tag }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image for this commit
        run: >
          docker push
          ghcr.io/documentat/${{ matrix.variant.image }}:${{ inputs.image_tag }}

      - name: Push image for this branch
        if: github.ref != 'refs/heads/master'
        run: >
          docker tag
          ghcr.io/documentat/${{ matrix.variant.image }}:${{ inputs.image_tag }}
          ghcr.io/documentat/${{ matrix.variant.image }}:${{ github.ref_name }}
          &&
          docker push
          ghcr.io/documentat/${{ matrix.variant.image }}:${{ github.ref_name }}

      - name: Push image for 'latest'
        if: github.ref == 'refs/heads/master'
        run: >
          docker tag
          ghcr.io/documentat/${{ matrix.variant.image }}:${{ inputs.image_tag }}
          ghcr.io/documentat/${{ matrix.variant.image }}:latest
          &&
          docker push
          ghcr.io/documentat/${{ matrix.variant.image }}:latest