on:
  workflow_call:

jobs:
  publish-latest:
    strategy:
      fail-fast: false
      matrix:
        image: [sobiraka, sobiraka-latex]

    name: ${{ matrix.image }}
    runs-on: self-hosted
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: >
          docker tag
          ghcr.io/documentat/${{ matrix.image }}:${{ github.sha }}
          ghcr.io/documentat/${{ matrix.image }}:latest

      - run: >
          docker push
          ghcr.io/documentat/${{ matrix.image }}:latest