name: Test & Publish

on: [push]

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  lint:
    name: Check code
    uses: ./.github/workflows/check-code.yml

  build-pip:
    name: Build Python package
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: make package IMAGE=sobiraka-package:${{ github.sha }}

  build-images:
    name: Build Docker images
    uses: ./.github/workflows/build-images.yml
    secrets: inherit

  check-docs:
    name: Check documentation
    needs: [build-images]
    uses: ./.github/workflows/check-docs.yml

  build-docs:
    name: Build documentation
    needs: [build-images, check-docs]
    uses: ./.github/workflows/build-docs.yml
    with:
      PUBLIC_REPOSITORY_URL: ${{ vars.PUBLIC_REPOSITORY_URL }}
      DOCKER_PROD_IMAGE: ${{ vars.DOCKER_PROD_IMAGE }}
    secrets: inherit