name: Test & Publish

on: [push]

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  lint:
    name: Check code
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: make lint

  build-pip:
    name: Build Python package
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - uses: actions/cache@v4
        with:
          key: setuptools
          path: ~/.cache/pip

      - run: pip install setuptools

      - name: Build package
        run: |
          python setup.py sdist
          echo ARTIFACT=dist/*.tar.gz >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python package
          path: ${{ env.ARTIFACT }}
          if-no-files-found: error

  build-images:
    name: Build Docker images
    uses: ./.github/workflows/build-images.yml

  check-docs:
    name: Check documentation
    needs: [build-images]
    uses: ./.github/workflows/check-docs.yml

  build-docs:
    name: Build documentation
    needs: [build-images]
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit